baseURL = "https://www.haiku-os.org/"
title = "Haiku Project"
copyright = "2001-2017 Haiku Inc."
languageCode = "en-us"

relativeURLs = true
buildDrafts = false
disableKinds = ["sitemap"]
theme = "shijin4"

[taxonomies]
  article = "articles"
  blog = "blog"
  tag = "tags"
  conference = "conference"
  news = "news"
[params]
  AuthorName = "Haiku Project"
  discourseUrl = "https://discuss.haiku-os.org/"
  BuildTypeIsDeploy = false		# Does not build sidebars & breadcrumbs when set to false
