baseURL = "https://www.haiku-os.org/"
title = "Haiku Project"
copyright = "2001-2017 Haiku Inc."
languageCode = "en-us"
canonifyURLs = true
disableSitemap = true
buildDrafts = false
[params]
  AuthorName = "Haiku Project"
  discourseUrl = "https://discuss.haiku-os.org/"
  BuildTypeIsDeploy = false		# Does not build sidebars & breadcrumbs when set to false
